### ISSUE TITLE
Error: node:internal/modules/cjs/loader:903

### ISSUE THREAD

**Issue by golyu** [anncwb/vben-admin-thin-next#4]
env:node:v15.0.1
       npm:6.14.8
       yarn:1.22.10
Download the latest,Run
```
yarn add
run serve
```

**Comment by golyu** [comment]
```
 esno ./build/script/preserve.ts && cross-env NODE_ENV=development vite
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/Users/user/OneDrive'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1155:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:74:3)
    at internal/main/repl.js:19:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
child_process.js:674
    throw err;
    ^

Error: Command failed: node -r /Users/user/OneDrive - FNC/custom_project/仓储系统/vben-admin-thin-next/node_modules/esm/esm.js -r /Users/user/OneDrive - FNC/custom_project/仓储系统/vben-admin-thin-n_modules/esbuild-register/register.js "./build/script/preserve.ts"
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Object.<anonymous> (/Users/user/OneDrive - FNC/custom_project/仓储系统/vben-admin-thin-next/node_modules/esno/esno.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 79239,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by 17702296834** [comment]
我也报这个错，请问您这边怎么解决的

**Comment by golyu** [comment]
路径的问题，中文路径和带空格路径都不行

17702296834 <notifications@github.com> 于 2020年11月11日周三 13:37写道：
